language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
    - git fetch --unshallow
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'ENV["PYTHON"]="";Pkg.build("SerialPorts");'
    - julia -e 'Pkg.test("SerialPorts", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SerialPorts")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
